server.port=${SERVER_PORT:8080}
spring.application.name=orq-service

# URL del data-ms (ms1-pos) — configurable via variable de entorno DATA_MS_URL
data.ms.url=${DATA_MS_URL:http://ms1-pos:8081}

# URL del ms2-online — configurable via variable de entorno DATA_MS2_URL
data.ms2.url=${DATA_MS2_URL:http://ms2-online:8083}
