server.port=${SERVER_PORT:8092}
spring.application.name=orq-ind

ms3.url=${MS3_URL:http://ms3-inventario:8084}
ms4.url=${MS4_URL:http://ms4-empleados:8085}

# BD IND — H2 en modo archivo
spring.datasource.url=jdbc:h2:file:/data/bd-ind;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
