server.port=${SERVER_PORT:8080}
spring.application.name=bff-service

# Orquestadores
orq.service.url=${ORQ_SERVICE_URL:http://orq-datos:8080}
orq.ind.url=${ORQ_IND_URL:http://orq-ind:8092}
orq.rep.url=${ORQ_REP_URL:http://orq-rep:8093}

# Microservicio de autenticacion
ms.auth.url=${MS_AUTH_URL:http://ms-auth:8090}
