server.port=${SERVER_PORT:8080}
spring.application.name=orq-datos

# URLs de los microservicios de ventas (MS1 y MS2)
data.ms.url=${DATA_MS_URL:http://ms1-pos:8081}
data.ms2.url=${DATA_MS2_URL:http://ms2-online:8083}

# BD DATOS — H2 en modo archivo (volumen Docker)
spring.datasource.url=jdbc:h2:file:/data/bd-datos;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
