server.port=${SERVER_PORT:8093}
spring.application.name=orq-rep

ms5.url=${MS5_URL:http://ms5-reportes:8086}

# BD REP — H2 en modo archivo
spring.datasource.url=jdbc:h2:file:/data/bd-rep;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
